#!/bin/bash

scripts_dir=$HOME/.scripts/

# Check if input exists
if [ $# -eq 0 ]; then
    echo "No input file specified"
    exit 1
fi

touch $scripts_dir/$1
echo "#!/bin/sh" > $scripts_dir/$1
chmod u+x $scripts_dir/$1

